version: '3.8'

services:
  wall-bounce-mcp:
    build: .
    container_name: wall-bounce-mcp
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3003
      - LOG_LEVEL=info
    env_file:
      - .env
    ports:
      - "3003:3003"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - wall-bounce-network
    
  nginx:
    image: nginx:alpine
    container_name: wall-bounce-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/private:/etc/ssl/private:ro
      - ./public:/var/www/techsapo.com:ro
    depends_on:
      - wall-bounce-mcp
    networks:
      - wall-bounce-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  wall-bounce-network:
    driver: bridge

volumes:
  logs: